Tu es un expert en jeu virtuel FIFA 18 Pénalty donc Je vais te fournir les scores passés ⚽️FIFA18 Penalty⚽️ d'où L'utilisateur va fournir obligatoirement le nom des deux équipes et tu va prédire  obligatoirement deux scores en fonction des scores que j'ai donné.
Score 1 avec un pourcentage 
Score 2 avec un pourcentage  en se basant sur les résultats des scores des équipes , Ces résultats montrent les scores les plus fréquents pour chaque paire d'équipes. Tu devrais obligatoirement te baser  pour donner le nombre total de buts .
1. Real Madrid 2:3 PSG 
2. Real Madrid 3:2 PSG 
3. Real Madrid 2:4 PSG 
1. Real Madrid 2:3 Arsenal 
2. Real Madrid 3:2 Arsenal 
3. Real Madrid 2:1 Arsenal 
4. Real Madrid 3:0 Arsenal 
8. Real Madrid 2:1 Arsenal 
9) Real Madrid 3:2 Arsenal 
11)Real Madrid 4:2 Liverpool 
12)Real Madrid 3:0 Arsenal 
19)Real Madrid 3:4Arsenal 
20) Real Madrid 3:4 Bayern Munich 
21) Real Madrid 4:5 Barcelone 
22) Real Madrid 3:1 Manchester city 
23) Real Madrid 2:3 Juventus 
24) Real Madrid 3:4 Arsenal 
25)Real Madrid 4:3 Arsenal 
26) Real Madrid 3:4 Arsenal 
27) Liverpool 0:2 Bayern 
28) Liverpool 2:3 Bayern 
29)Liverpool 4:1 Bayern
37)PSG 2:4 Manchester City 
38)PSG 3:4 Manchester City 
39)PSG 2:4 Manchester City 
40)Barcelona 3:4 Real Madrid 
41)Barcelona 4:2 Real Madrid
42)Barcelona 2:3 Real Madrid 
43) Barcelona 4:3 Real Madrid 
44) Barcelona 3:4 Real Madrid 
45)Juventus 3:2Real Madrid
41)Juventus 2:1 Real Madrid 
45)Juventus 2:3 Real Madrid 
46)Juventus 4:3 Real Madrid 
52)Juventus 3:4 Real Madrid
54) Juventus 3:4 Bayern Munich 
55) Juventus 1:2 Manchester city 
56) Juventus 4:2 Arsenal 
57)Juventus 3:2 Arsenal 
58) Juventus 3:4 Liverpool 
59) Barcelone 4:1 Real Madrid 
60) Arsenal 3:4 Real Madrid 
61) Bayern Munich 3:4 Real Madrid 
62) Barcelone 1:2 Real Madrid 
65) Juventus 1:3 Real Madrid 
66) Barcelone 3: 2 Real Madrid 
67) Barcelone 1: 2 Real Madrid 
68) Barcelone 2:3 Real Madrid 
69) Bayern 4:5 Real Madrid 
70) Barcelone 1:2 Real Madrid 
71)PSG 1:3 Real Madrid 
72) Bayern Munich 2:3 Barcelone 
73) Liverpool 1:2 Bayern Munich 
74) Liverpool 3:2 Bayern Munich 
75) Bayern Munich 1:2 Barcelone 
76) Bayern Munich 3:4 Real Madrid 
77) Bayern Munich 4:2 Barcelone 
78) Arsenal 3:4 Bayern Munich 
79) Arsenal 4:5 Bayern Munich 
80) Bayern Munich 4:2 PSG
81) Liverpool 2:4 Bayern Munich 
82) Liverpool 4:5 Bayern Munich 
83) Bayern Munich 1:2 Barcelone 
84) Liverpool 3:2 Bayern Munich 
85) Arsenal 3:2 Bayern Munich 
86)Bayern Munich 2:3 PSG
87) Liverpool 4:3 Bayern Munich 
88) Bayern Munich 5:6 Manchester city 
89) Liverpool 4:5 Bayern Munich 
90) Bayern Munich 2:0 Liverpool 
91) Liverpool 6:7 Bayern Munich 
90) Bayern Munich 3:4 Liverpool 
91) Bayern Munich 2:3 Liverpool 
94) Liverpool 3:2 Bayern Munich 
95) Real Madrid 3:4 Bayern Munich 
96) Liverpool 1:2 Bayern Munich 
97) Bayern Munich 4:5 Real Madrid 
98) Liverpool 2-0 Bayern Munich 
99) Liverpool 2:4 Bayern Munich 
100) Bayern Munich 3:2 Juventus 
101) Bayern Munich 3:2 Arsenal 
102) Arsenal 4:3 Bayern Munich 
103) Arsenal 2:3 Bayern Munich 
104) Bayern Munich 4:3 Liverpool 
105) PSG 3:1 Bayern Munich 
108) Bayern Munich 3:4 Liverpool 
109) Arsenal 3:1 Bayern Munich 
110) Arsenal 1:3 Bayern Munich 
111) Barcelone 2:1 Juventus 
112) Liverpool 0:3 Arsenal 
113)Manchester city 3:2 Bayern Munich 
114) Manchester city 3:0 PSG
115) Bayern Munich 2:3 Barcelone 
116)PSG3:2 Liverpool 
123) Manchester city 3 :2 PSG
124) Manchester city 1:2 PSG
125) Manchester city 3 :1 Juventus 
126) Manchester 0:3 PSG
127) Liverpool 3:2 Manchester city 
128) Manchester city 3:4 Juventus 
129)PSG 4:2 Manchester city 
130) Manchester city 2:3 PSG
132) Barcelone 3:2 Manchester city 
133) Manchester city 3:1 PSG
134) Real Madrid 4:2 Manchester city 
135) Manchester city 3:2 PSG
136) Manchester city 2:3 PSG
1. Real Madrid 2:3 PSG 
2. Real Madrid 3:2 PSG 
3. Real Madrid 2:4 PSG 
1. Real Madrid 2:3 Arsenal 
2. Real Madrid 3:2 Arsenal 
3. Real Madrid 2:1 Arsenal 
4. Real Madrid 3:0 Arsenal 
8. Real Madrid 2:1 Arsenal 
9) Real Madrid 3:2 Arsenal 
11)Real Madrid 4:2 Liverpool 
12)Real Madrid 3:0 Arsenal 
19)Real Madrid 3:4Arsenal 
20) Real Madrid 3:4 Bayern Munich 
21) Real Madrid 4:5 Barcelone 
22) Real Madrid 3:1 Manchester city 
23) Real Madrid 2:3 Juventus 
24) Real Madrid 3:4 Arsenal 
25)Real Madrid 4:3 Arsenal 
26) Real Madrid 3:4 Arsenal 
27) Liverpool 0:2 Bayern 
28) Liverpool 2:3 Bayern 
29)Liverpool 4:1 Bayern
37)PSG 2:4 Manchester City 
38)PSG 3:4 Manchester City 
39)PSG 2:4 Manchester City 
40)Barcelona 3:4 Real Madrid 
41)Barcelona 4:2 Real Madrid
42)Barcelona 2:3 Real Madrid 
43) Barcelona 4:3 Real Madrid 
44) Barcelona 3:4 Real Madrid 
45)Juventus 3:2Real Madrid
41)Juventus 2:1 Real Madrid 
45)Juventus 2:3 Real Madrid 
46)Juventus 4:3 Real Madrid 
52)Juventus 3:4 Real Madrid
54) Juventus 3:4 Bayern Munich 
55) Juventus 1:2 Manchester city 
56) Juventus 4:2 Arsenal 
57)Juventus 3:2 Arsenal 
58) Juventus 3:4 Liverpool 
59) Barcelone 4:1 Real Madrid 
60) Arsenal 3:4 Real Madrid 
61) Bayern Munich 3:4 Real Madrid 
62) Barcelone 1:2 Real Madrid 
65) Juventus 1:3 Real Madrid 
66) Barcelone 3: 2 Real Madrid 
67) Barcelone 1: 2 Real Madrid
68) Barcelone 2:3 Real Madrid 
69) Bayern 4:5 Real Madrid 
70) Barcelone 1:2 Real Madrid 
71)PSG 1:3 Real Madrid 
72) Bayern Munich 2:3 Barcelone 
73) Liverpool 1:2 Bayern Munich 
74) Liverpool 3:2 Bayern Munich 
75) Bayern Munich 1:2 Barcelone 
76) Bayern Munich 3:4 Real Madrid 
77) Bayern Munich 4:2 Barcelone 
78) Arsenal 3:4 Bayern Munich 
79) Arsenal 4:5 Bayern Munich 
80) Bayern Munich 4:2 PSG
81) Liverpool 2:4 Bayern Munich 
82) Liverpool 4:5 Bayern Munich 
83) Bayern Munich 1:2 Barcelone 
84) Liverpool 3:2 Bayern Munich 
85) Arsenal 3:2 Bayern Munich 
86)Bayern Munich 2:3 PSG
87) Liverpool 4:3 Bayern Munich 
88) Bayern Munich 5:6 Manchester city 
89) Liverpool 4:5 Bayern Munich 
90) Bayern Munich 2:0 Liverpool 
91) Liverpool 6:7 Bayern Munich 
90) Bayern Munich 3:4 Liverpool 
91) Bayern Munich 2:3 Liverpool 
94) Liverpool 3:2 Bayern Munich 
95) Real Madrid 3:4 Bayern Munich 
96) Liverpool 1:2 Bayern Munich 
97) Bayern Munich 4:5 Real Madrid 
98) Liverpool 2-0 Bayern Munich 
99) Liverpool 2:4 Bayern Munich 
100) Bayern Munich 3:2 Juventus 
101) Bayern Munich 3:2 Arsenal 
102) Arsenal 4:3 Bayern Munich 
103) Arsenal 2:3 Bayern Munich 
104) Bayern Munich 4:3 Liverpool 
105) PSG 3:1 Bayern Munich 
108) Bayern Munich 3:4 Liverpool 
109) Arsenal 3:1 Bayern Munich 
110) Arsenal 1:3 Bayern Munich 
111) Barcelone 2:1 Juventus 
112) Liverpool 0:3 Arsenal 
113)Manchester city 3:2 Bayern Munich 
114) Manchester city 3:0 PSG
115) Bayern Munich 2:3 Barcelone 
116)PSG3:2 Liverpool 
123) Manchester city 3 :2 PSG
124) Manchester city 1:2 PSG
125) Manchester city 3 :1 Juventus 
126) Manchester 0:3 PSG
127) Liverpool 3:2 Manchester city 
128) Manchester city 3:4 Juventus 
129)PSG 4:2 Manchester city 
130) Manchester city 2:3 PSG
132) Barcelone 3:2 Manchester city 
133) Manchester city 3:1 PSG
134) Real Madrid 4:2 Manchester city 
135) Manchester city 3:2 PSG
136) Manchester city 2:3 PSG
PSG (3:2) Manchester City 
N148. Barcelone (1:3) Real
N149. Real Madrid (1:2) Arsenal 
N150. Real Madrid (3:4) Arsenal 
N151. Liverpool (1:3) PSG 
N152. Manchester City (3:0) PSG 
N153. Bayern (3:4) Liverpool 
N154. Juventus (5:4) Bayern 
N155. Arsenal (5:3) Juventus N156. Barcelone (4:5) Manchester City 
N157. PSG (1:2) Réel N158. 
PSG (4:5) Real Madrid 
N159. Real Madrid (3:4) Arsenal
N160. Manchester City (4:5) Arsenal
N161. Manchester City (4:2) PSG
N162. Liverpool (1:3) Bayern
N164. Arsenal (4:2) Juventus 
N165. Juventus (4:2) Barcelone


